## 
## Cadence First Encounter "v08.10-p004_1 ((32bit) 11/04/2008 14:34 (Linux 2.6))"
## Mon Oct  5 00:53:17 2026
## 
set sdc_version 1.4
current_design sys_top
create_clock [get_ports {UART_CLK}]  -name UART_clk -period 271.29 -waveform {0 135.65}
set_clock_transition  -rise -min 0.05 [get_clocks {UART_clk}]
set_clock_transition  -rise -max 0.05 [get_clocks {UART_clk}]
set_clock_transition  -fall -min 0.05 [get_clocks {UART_clk}]
set_clock_transition  -fall -max 0.05 [get_clocks {UART_clk}]
create_clock [get_ports {REF_CLK}]  -name Ref_clk -period 10 -waveform {0 5}
set_clock_transition  -rise -min 0.05 [get_clocks {Ref_clk}]
set_clock_transition  -rise -max 0.05 [get_clocks {Ref_clk}]
set_clock_transition  -fall -min 0.05 [get_clocks {Ref_clk}]
set_clock_transition  -fall -max 0.05 [get_clocks {Ref_clk}]
create_clock [get_ports {scan_clk}]  -name scan_clk -period 100 -waveform {0 50}
create_generated_clock -name Gated_clk -source [get_ports {REF_CLK}] -combinational -master_clock [get_clocks {Ref_clk}] -add [get_pins {ALU_CG/U2/Y}]
create_generated_clock -name Tx_clk -source [get_ports {UART_CLK}] -divide_by 32 -master_clock [get_clocks {UART_clk}] -add [get_pins {TX_CLK/U40/Y}]
create_generated_clock -name Rx_clk -source [get_ports {UART_CLK}] -divide_by 1 -master_clock [get_clocks {UART_clk}] -add [get_pins {RX_CLK/U18/Y}]
set_propagated_clock  [get_pins {ALU_CG/U2/Y}]
set_propagated_clock  [get_pins {TX_CLK/U40/Y}]
set_propagated_clock  [get_ports {UART_CLK}]
set_propagated_clock  [get_ports {scan_clk}]
set_propagated_clock  [get_ports {REF_CLK}]
set_propagated_clock  [get_pins {RX_CLK/U18/Y}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -rise -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -fall -max -pin Y -from_pin A [get_ports {SI[0]}]
set_load -pin_load -max  0.1  [get_ports {SO[2]}]
set_load -pin_load -min  0.1  [get_ports {SO[2]}]
set_load -pin_load -max  0.1  [get_ports {SO[1]}]
set_load -pin_load -min  0.1  [get_ports {SO[1]}]
set_load -pin_load -max  0.1  [get_ports {SO[0]}]
set_load -pin_load -min  0.1  [get_ports {SO[0]}]
set_load -pin_load -max  0.1  [get_ports {UART_TX_O}]
set_load -pin_load -min  0.1  [get_ports {UART_TX_O}]
set_load -pin_load -max  0.1  [get_ports {parity_error}]
set_load -pin_load -min  0.1  [get_ports {parity_error}]
set_load -pin_load -max  0.1  [get_ports {framing_error}]
set_load -pin_load -min  0.1  [get_ports {framing_error}]
set_case_analysis 0 [get_ports {SE}]
set_case_analysis 1 [get_ports {test_mode}]
set_input_delay -add_delay 20 -clock [get_clocks {scan_clk}] [get_ports {SI[2]}]
set_input_delay -add_delay 20 -clock [get_clocks {scan_clk}] [get_ports {SI[0]}]
set_input_delay -add_delay 54.258 -clock [get_clocks {Rx_clk}] [get_ports {UART_RX_IN}]
set_input_delay -add_delay 20 -clock [get_clocks {scan_clk}] [get_ports {SI[1]}]
set_input_delay -add_delay 20 -clock [get_clocks {scan_clk}] [get_ports {SE}]
set_output_delay -add_delay 20 -clock [get_clocks {scan_clk}] [get_ports {SO[1]}]
set_output_delay -add_delay 54.258 -clock [get_clocks {Rx_clk}] [get_ports {framing_error}]
set_output_delay -add_delay 20 -clock [get_clocks {scan_clk}] [get_ports {SO[2]}]
set_output_delay -add_delay 1736.3 -clock [get_clocks {Tx_clk}] [get_ports {UART_TX_O}]
set_output_delay -add_delay 20 -clock [get_clocks {scan_clk}] [get_ports {SO[0]}]
set_output_delay -add_delay 54.258 -clock [get_clocks {Rx_clk}] [get_ports {parity_error}]
set_clock_uncertainty 0.1 -hold [get_clocks {Gated_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {Gated_clk}]
set_clock_uncertainty 0.1 -hold [get_clocks {Ref_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {Ref_clk}]
set_clock_uncertainty 0.1 -hold [get_clocks {Tx_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {Tx_clk}]
set_clock_uncertainty 0.1 -hold [get_clocks {Rx_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {Rx_clk}]
set_clock_uncertainty 0.1 -hold [get_clocks {UART_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {UART_clk}]
set_clock_groups -name UART_clk_1 -asynchronous  -group  [get_clocks {Rx_clk Tx_clk UART_clk}] -group  [get_clocks {Gated_clk Ref_clk}]
set_clock_groups -name scan_clk_1 -logically_exclusive  -group  [get_clocks {scan_clk}] -group  [get_clocks {Rx_clk Tx_clk Gated_clk UART_clk Ref_clk}]
